language: java
jdk:
  - oraclejdk8
dist: trusty
install: true

branches:
  only:
    - master
    - develop
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=API4KBs_kmdp-language -Ppublic -q

deploy:
  - provider: script
    script: mvn deploy -DskipTests -Ppublic -s .travis.settings.xml
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: mvn deploy -DskipTests -Ppublic -s .travis.settings.xml
    skip_cleanup: true
    on:
      branch: develop

addons:
  sonarcloud:
    organization: "api4kbs"
    token:
      secure: "DOfsdz11tFi+0+5TqnpH6xf1xxq2xl5lFO0udnYi66ZiDqAl3yfFFHUhvKvZSSMnEk7TFkvSEQszANjJ0jXgXlWAVxA324y6TSxpB52KyJB80BMDSYuft/JLXpF+p7VJLrzGtYiS8022CGxj/aSQgt0/y2coN8YdgYIfrPvXsQYa1uwgZ0jRL7X5g2Lx7B6wC5YCZmnLUSd8IeLz512ae8iV6AWJfnTN79j2p8tPI7Ly6s6TQTNSKKNc9gDhGU40LEdw0gi8iOG7blbxwaWI72npW66DfmLJiMbsJzOd5p1tk1A9ExjqqLJbdnCfF86eGAbx3bV8rIyQAWl6nZnLGB+4SHKWNsuMFpscgNrLVmYYDNnMojZETF20VWsXoeu+CpV5KRfgiVHFEwR0F5f5orhP43sy/Atx2J/GQ/TqwIUaiUdQ7rwEmg9skTgIdw2Ktoup6lXdkfS/un82gYrGHeRe1ORn+G+vrtyp08yM1ZlWhI6ou1cUQbdMlA2nwemBndi+Yo6xi0ckZJQc3gJ7x/6IibovkdmTHwbmkV0a1I9//3VnKGCByp0jgRF/CFfblXRG0rz2BG9PW+xRbI0gNoyFuUl9CSC9y3ImJaN55nltUD72Bs1lZNJqFvuYQ+xQb8fsam4A5eAR/zArDehoXQkAXbJ3reQZAU9ASIiR9OI="

env:
  global:
  - secure: Uu0/wwlbN2IPVt12xvNM0HtJ0zYr7S/QSH5bQF1MxD9GC3Ez8Sb0LGCFvo0EZuEUuaOBMwrYO8S8qstmL+TCgA+J1Peh+YWO2hWRUI4CXJqfbGpk+S7gCh+YaABkmKuUTL+IQKjTp3gr1mX/aTAP/F1rikAz+j0DW6fKti0NoSMoeTfEBuI+A2DfIvnsot/2dbrrur91BVMLTBA9xzhwPBwZB1xnQMC+2JYqhO8nXt2D05ekx0m92Qgwqjc6s0pccpV9uFs8j2auDrebh3CghQQLqMy3W2Iq0Vup/jYFuY4JT5W9cX8cXjytFaJpnFY3IfTH7EeISfVbZf1S2CbpaZPW14X62bahWuAsezvbycGROpiEZukCBMB/jhMik2z8yKQrpR2LS+LdBcRzPy7NarSrc9CpthzFYmSN5kFzNpouK8c+J9u3eYQ+Y66dZxEgmBId9CJ1Rq6LGVtOJJmWzSvLiPGl+7JhJtWuEJof3N6oyu78jhGWSx/BVwcGPMQAGWRwI3Z6sz9GejWJoWksZz7CqIsaxZslhRquK4RPBjMciYGyrbjBz3bEScUR6xlfAu2kZipuIf0arVvXGvX3and4Vna1gXlM8Uz3Y25WASIoP6BRZbpwrNcwbz2n8vQlOb2Hd4s5C/PKa/OUwgZHcwR8P1nAZK4mWSGHALBQsXw=
  - secure: JfLeZG7JuzzRQrEQF4k+RU3uZF8bL13TwyUeAo88k6c5UnH2TEWAJigQ/nSU/sZHWfwFPkfTDawHo9tbWHzn1TOAWzDzXaFVo/YRf1rZN4aGg8uheejFoWulZgFIXuht/XCzRGRBjodEMZEGkPlZDEDeJyUpKkYQRWJTdR2MMcp4DiZsFWWkZuEpiBcU+/kOaTUB+WUxKmKtilpAGJdpVONrZqIR3uWqYNyxc7Uj7Qz02x2qGF20ktNVWQJ5px181tGmxUaVkX0NZZxsUMF+AVAY8yZDdFXrzNQD7vI/4/FgnifUHtMOVOvC19iKOysRz5AUZJFNCM8jGcXValzZpYvl5qSus8bF3yVVJ260WHniweJN51/zTfyW3h4fqZSrbTZKOLt9cg07ovqoFt7WsOQem88LsL0tU0s57PbVC3Ufj4h7k8Fv9ddpZeBSdRtbCOseRGVjZEM++vL0KpuPSt3dra4XXanu+SfHiV2o4V1BiIE4y6eHPiv+sOFRJjDV+8RBABhCN3f07Po5+pJQS6m4TloY+PBUUwznkROa1mxmejqXG2naqgOMDjicFIfUmLRnBXpHlcMa7JP+oGDizhqfR6BC27NwMI4u3Cnhzw2yXnS7Fl6TlZ7a1PvSxiIAqz9FXUHbM5Eh9InBjohVN2+MXNgCukTiC1N050J/3SM=
  - secure: lhHt787DRezxK1TcIukJZ6gfbd+iEnY9b+ylMKcyX/rQtDRkDB5B02Ho40ISEFMQasdp2vpCrO1/cBRmUJFhU8aSSRacjlGPj1mSw9dKIj5iAZCgDmoFWwFk0QFojXskn5BXOZWPhTCb+L2jqejG8qAm7rrjQm+zGChPyz59wwQjn5jOBuLpC2MDf0dv/VPKhQEz184SLZ+/0pWKh/V7EZhS+5Wiz0cIoRvQfYRfORNhs6BNZGuJ7jsy70xIY1TaqG7CPyDHcjjNw1qnFgjiSez7dsucZu7qxEw2SOwqyPeJbTWTHZQGg7Ml4It8DW7a5TuUWL2nfAwPPDyOGGBKiYdZisbTRGIYp3CqQYJoWymdL6atMIZBh9Jbsco2PYcaBud5w/iQynglcZmpnGWS/rXpG+my+Bpy8ALT6Ak+Fzw344rr+NujroOgvFMn/aAVH7u4P4ma7azhFKKxZJIPkp6uo64hy3BxrLfxCXz6SNoFm1qg3j52fXRvb4sFsiEyknA0gmf4Xw9WYO4zoMfI6F5lzBcQxDYwK5hwVQpv0o+65J8k4eaP3wVbeTq82XEnx3tMxx9enVH0z8KNZ7w76Rr/dxKPs3m+AJlHxPwN+nczAVDAAtOGdft8PJQPyyPiW7NTg9037ZUZgGdrovj24Avr4EYC3U7fAE2nflIVh68=
